# Generated by Django 2.1.1 on 2018-09-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=200)),
                ('salt', models.BinaryField(max_length=32)),
                ('cookie', models.BinaryField(max_length=32)),
                ('admin', models.BooleanField()),
            ],
        ),
    ]
